server:
  port: 8080
  servlet:
    context-path: /library

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1911

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    port: 587
    username: dev.nguyenphuong@gmail.com
    password: cwggvxkmawsmjecj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600000 # in second
  refreshable-duration: 36000 # in seconds
